name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    container:
      image: node:lts-alpine

    steps:
      - name: Install SSH Client and Dependencies
        run: apk add --no-cache openssh

      - name: Install PNPM
        run: npm install -g pnpm
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: pnpm install

      - name: Build the application
        run: pnpm run build

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VEGETA_SERVER }}

      - name: Deploy via SSH
        env:
          VEGETA_SERVER_IP: ${{ secrets.VEGETA_SERVER_IP }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL}}
          MONGODB_URL: ${{ secrets.MONGODB_URL}}
          LNBITS_APIKEY: ${{ secrets.LNBITS_APIKEY}}
          OPENNODE_KEY: ${{ secrets.OPENNODE_KEY}}
          PAYPAL_ENV: ${{ secrets.PAYPAL_ENV}}
          NEXT_PUBLIC_PAYPAL_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_PAYPAL_CLIENT_ID}}
          PAYPAL_SECRET: ${{ secrets.PAYPAL_SECRET}}
          PAYPAL_SANDBOXURL: ${{ secrets.PAYPAL_SANDBOXURL}}
          NEXT_PUBLIC_DOMAIN: ${{ secrets.DOMAIN }}
          NEXT_PUBLIC_OWNER_NAME: ${{ secrets.OWNER_NAME }}
          NEXT_PUBLIC_COMPANY_NAME: ${{ secrets.COMPANY_NAME }}
          NEXT_PUBLIC_POSTFACH: ${{ secrets.POSTFACH }}
          NEXT_PUBLIC_ADDR_STREET: ${{ secrets.ADDR_STREET }}
          NEXT_PUBLIC_ADDR_ZIP_AND_CITY: ${{ secrets.ADDR_ZIP_AND_CITY }}
          NEXT_PUBLIC_PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
          NEXT_PUBLIC_UST_NR: ${{ secrets.UST_NR }}
          NEXT_PUBLIC_EMAIL_ADDRESS: ${{ secrets.NEXT_PUBLIC_EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          IMAP_MAIL_SERVER_OUT: ${{ secrets.IMAP_MAIL_SERVER_OUT }}
          IMAP_MAIL_SERVER_PORT_OUT: ${{ secrets.IMAP_MAIL_SERVER_PORT_OUT }}       
        run: |
          ssh -o StrictHostKeyChecking=no vegeta@${{ secrets.VEGETA_SERVER_IP }} << 'EOF'
            cd ~/vanity2/vanity-service
            git pull origin main
            echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL}}" > .env.local
            echo "MONGODB_URL=${{ secrets.MONGODB_URL}}" >> .env.local
            echo "LNBITS_APIKEY=${{ secrets.LNBITS_APIKEY}}" >> .env.local
            echo "OPENNODE_KEY=${{ secrets.OPENNODE_KEY}}" >> .env.local
            echo "PAYPAL_ENV=${{ secrets.PAYPAL_ENV}}" >> .env.local
            echo "NEXT_PUBLIC_PAYPAL_CLIENT_ID=${{ secrets.NEXT_PUBLIC_PAYPAL_CLIENT_ID}}" >> .env.local
            echo "PAYPAL_SECRET=${{ secrets.PAYPAL_SECRET}}" >> .env.local
            echo "PAYPAL_SANDBOXURL=${{ secrets.PAYPAL_SANDBOXURL}}" >> .env.local
            echo "NEXT_PUBLIC_EMAIL_ADDRESS=${{ secrets.NEXT_PUBLIC_EMAIL_ADDRESS }}" >> .env.local
            echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> .env.local
            echo "IMAP_MAIL_SERVER_OUT=${{ secrets.IMAP_MAIL_SERVER_OUT }}" >> .env.local
            echo "IMAP_MAIL_SERVER_PORT_OUT=${{ secrets.IMAP_MAIL_SERVER_PORT_OUT }}" >> .env.local
            echo "NEXT_PUBLIC_COMPANY_NAME=${{ secrets.NEXT_PUBLIC_COMPANY_NAME }}" >> .env.local
            echo "NEXT_PUBLIC_DOMAIN=${{ secrets.NEXT_PUBLIC_DOMAIN }}" >> .env.local
            echo "NEXT_PUBLIC_OWNER_NAME=${{ secrets.NEXT_PUBLIC_OWNER_NAME }}" >> .env.local
            echo "NEXT_PUBLIC_POSTFACH=${{ secrets.NEXT_PUBLIC_POSTFACH }}" >> .env.local
            echo "NEXT_PUBLIC_ADDR_STREET=${{ secrets.NEXT_PUBLIC_ADDR_STREET }}" >> .env.local
            echo "NEXT_PUBLIC_ADDR_ZIP_AND_CITY=${{ secrets.NEXT_PUBLIC_ADDR_ZIP_AND_CITY }}" >> .env.local
            echo "NEXT_PUBLIC_PHONE_NUMBER=${{ secrets.NEXT_PUBLIC_PHONE_NUMBER }}" >> .env.local
            echo "NEXT_PUBLIC_UST_NR=${{ secrets.NEXT_PUBLIC_UST_NR }}" >> .env.local
            pnpm install
            pnpm run build
            pm2 reload vanity-service --update-env
          EOF

